FROM ubuntu:20.04

EXPOSE 8000

WORKDIR /srv/server

COPY requirements.txt /root/requirements.txt
COPY sources.list /root/sources.list

RUN apt-get -y update && apt-get -y install ca-certificates && \
    cp /root/sources.list /etc/apt/sources.list

RUN apt-get -y update && apt-get -y upgrade && apt-get -y install python3-pip

RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip3 install -r /root/requirements.txt
